FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% set libvirt_group = 'libvirtd' %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        libvirt-daemon \
        libguestfs \
        qemu-system-x86 \
        libvirt-daemon-driver-nwfilter \
        libvirt-daemon-config-nwfilter \
        libvirt-daemon-driver-lxc \
        ceph-common \
    && yum clean all \
    && usermod -a -G nova qemu


{% elif base_distro in ['ubuntu', 'debian'] %}

{% if base_distro == 'ubuntu' %}
{% set packages =
      ' xen-utils-4.6'
%}
{% elif base_distro == 'debian' %}
{% set packages =
      ' xen-utils-4.4 usermode'
%}
{% set libvirt_group = 'libvirt' %}
{% endif %}

ENV DEBIAN_FRONTEND noninteractive
RUN echo 'APT::Default-Release "stable";' > /etc/apt/apt.conf.d/99defaultrelease
RUN echo " deb http://httpredir.debian.org/debian testing  main \n\
deb http://httpredir.debian.org/debian testing-updates main \n\
deb http://security.debian.org testing/updates main"  > /etc/apt/sources.list.d/testing.list

RUN apt-get update && apt-get -t testing -y install --no-install-recommends \
        ceph-common \
        libvirt-bin \
        dmidecode \
        pm-utils \
        qemu \
        qemu-block-extra \
        ebtables \
        {{ packages }} \
    && apt-get clean \
    && mkdir -p /etc/ceph \
    && rm -f /etc/libvirt/qemu/networks/default.xml /etc/libvirt/qemu/networks/autostart/default.xml \
    && usermod -a -G {{ libvirt_group }} nova


{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{{ include_footer }}
