FROM {{ namespace }}/{{ image_prefix }}ironic-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-ironic-conductor \
        qemu-img \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get -y install --no-install-recommends \
        ironic-conductor \
        qemu-utils \
        ipmitool \
    && apt-get clean

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
RUN wget https://kojipkgs.fedoraproject.org//packages/ipmitool/1.8.15/4.fc23/x86_64/ipmitool-1.8.15-4.fc23.x86_64.rpm && yum -y install ipmitool-1.8.15-4.fc23.x86_64.rpm
RUN yum -y install \
        qemu-img \
    && yum clean all

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get -y install --no-install-recommends \
        qemu-utils \
        ipmitool \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER ironic
