FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}

# Currently not supported

{% elif install_type == 'source' %}

ADD searchlight-archive /searchlight-source
RUN ln -s searchlight-source/* searchlight \
    && mkdir -p /etc/searchlight/ \
    && mkdir -p /var/log/searchlight/ \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install /searchlight

{% endif %}
