FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-nova-compute \
        openvswitch \
        sysfsutils \
        ceph-common \
        genisoimage \
        iscsi-initiator-utils \
        python-rtslib \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

# ironic as workaround https://bugs.launchpad.net/packstack/+bug/1430388
RUN apt-get -y install --no-install-recommends \
        nova-compute \
        openvswitch-switch \
        sysfsutils \
        ceph-common \
        ironic-common \
        python-ironicclient \
        genisoimage \
        open-iscsi \
        python-rtslib \
    && apt-get clean \
    && rm -f /etc/nova/nova-compute.conf

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        libvirt-devel \
        openvswitch \
        qemu-img \
        sysfsutils \
        ceph-common \
        genisoimage \
        iscsi-initiator-utils \
        python-rtslib-fb \
    && yum clean all

    {% elif base_distro in ['ubuntu', 'debian'] %}

ENV DEBIAN_FRONTEND noninteractive
RUN echo 'APT::Default-Release "stable";' > /etc/apt/apt.conf.d/99defaultrelease
RUN echo " deb http://httpredir.debian.org/debian testing  main \n\
deb http://httpredir.debian.org/debian testing-updates main \n\
deb http://security.debian.org testing/updates main"  > /etc/apt/sources.list.d/testing.list

RUN apt-get update && apt-get -t testing -y install --no-install-recommends \
        libvirt-dev \
        qemu-utils \
        ceph-common \
        genisoimage \
        open-iscsi \
        python-rtslib-fb \
    && apt-get clean \
    && mkdir -p /etc/ceph

    {% endif %}

RUN /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt libvirt-python

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_nova_extend_start
RUN chmod 755 /usr/local/bin/kolla_nova_extend_start \
    && rm -f /etc/machine-id

ENV PATH $PATH:/lib/udev

{{ include_footer }}

USER nova
